@host=https://localhost:7217

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "JohnDoe@gmail.com",
    "password": "12345678"
}
